In [1]:
from pathlib import Path
import pandas as pd

In [2]:
dirpath = Path("/Users/halu/remote_connections/olm/storage/big-icir-datasets/EGAD00001003977/metadata")
assert dirpath.exists()

In [24]:
filepath = dirpath / "experiments.tsv"
assert filepath.exists()
df = pd.read_csv(filepath , sep="\t")
print(df.nunique())
df.head()

accession_id                     348
design_description                 1
library_name                       1
library_construction_protocol      1
paired_nominal_length              1
paired_nominal_sdev                1
platform                           1
model                              1
library_layout                     1
library_strategy                   1
library_source                     1
library_selection                  1
extra_attributes                   1
study_accession_id                 1
submission_accession_id            1
created_at                         6
edited_at                          6
dtype: int64

,accession_id,design_description,library_name,library_construction_protocol,paired_nominal_length,paired_nominal_sdev,platform,model,library_layout,library_strategy,library_source,library_selection,extra_attributes,study_accession_id,submission_accession_id,created_at,edited_at
0,EGAX00001607543,TruSeq RNA Exome (RNA access),\N,\N,50,\N,ILLUMINA,Illumina HiSeq 2500,PAIRED,RNA-Seq,TRANSCRIPTOMIC,other,\N,EGAS00001002556,EGA00001409650,2018-02-16 23:51:05+01,2018-02-16 23:51:05+01
1,EGAX00001607544,TruSeq RNA Exome (RNA access),\N,\N,50,\N,ILLUMINA,Illumina HiSeq 2500,PAIRED,RNA-Seq,TRANSCRIPTOMIC,other,\N,EGAS00001002556,EGA00001409650,2018-02-16 23:51:06+01,2018-02-16 23:51:06+01
2,EGAX00001607545,TruSeq RNA Exome (RNA access),\N,\N,50,\N,ILLUMINA,Illumina HiSeq 2500,PAIRED,RNA-Seq,TRANSCRIPTOMIC,other,\N,EGAS00001002556,EGA00001409650,2018-02-16 23:51:06+01,2018-02-16 23:51:06+01
3,EGAX00001607546,TruSeq RNA Exome (RNA access),\N,\N,50,\N,ILLUMINA,Illumina HiSeq 2500,PAIRED,RNA-Seq,TRANSCRIPTOMIC,other,\N,EGAS00001002556,EGA00001409650,2018-02-16 23:51:06+01,2018-02-16 23:51:06+01
4,EGAX00001607547,TruSeq RNA Exome (RNA access),\N,\N,50,\N,ILLUMINA,Illumina HiSeq 2500,PAIRED,RNA-Seq,TRANSCRIPTOMIC,other,\N,EGAS00001002556,EGA00001409650,2018-02-16 23:51:06+01,2018-02-16 23:51:06+01

In [25]:
filepath = dirpath / "run_sample.tsv"
assert filepath.exists()
df = pd.read_csv(filepath , sep="\t")
print(df.nunique())
df.head()

sample_alias               348
sample_accession_id        348
biosample_id               348
run_accession_id           348
experiment_accession_id    348
study_accession_id           1
sample_attributes          348
dtype: int64

,sample_alias,sample_accession_id,biosample_id,run_accession_id,experiment_accession_id,study_accession_id,sample_attributes
0,SAM00b9e5c52da9,EGAN00001627928,SAMEA104453869,EGAR00001652884,EGAX00001607543,EGAS00001002556,Baseline ECOG Score=1;Best Confirmed Overall R...
1,SAM0257bbbbd388,EGAN00001627900,SAMEA104453841,EGAR00001652885,EGAX00001607544,EGAS00001002556,Baseline ECOG Score=1;Best Confirmed Overall R...
2,SAM025b45c27e05,EGAN00001627771,SAMEA104453712,EGAR00001652886,EGAX00001607545,EGAS00001002556,Baseline ECOG Score=0;Best Confirmed Overall R...
3,SAM032c642382a7,EGAN00001627721,SAMEA104453662,EGAR00001652887,EGAX00001607546,EGAS00001002556,Baseline ECOG Score=1;Best Confirmed Overall R...
4,SAM04c589eb3fb3,EGAN00001627992,SAMEA104453933,EGAR00001653159,EGAX00001607818,EGAS00001002556,Baseline ECOG Score=2;Best Confirmed Overall R...

In [26]:
filepath = dirpath / "runs.tsv"
assert filepath.exists()
df = pd.read_csv(filepath , sep="\t")
print(df.nunique())
df.head()

accession_id               348
run_file_type                1
extra_attributes             1
sample_accession_id        348
experiment_accession_id    348
submission_accession_id      1
created_at                   5
edited_at                    2
dtype: int64

,accession_id,run_file_type,extra_attributes,sample_accession_id,experiment_accession_id,submission_accession_id,created_at,edited_at
0,EGAR00001652884,fastq,\N,EGAN00001627928,EGAX00001607543,EGA00001409650,2018-02-16 23:51:10+01,2024-01-17 16:29:41.757737+01
1,EGAR00001652885,fastq,\N,EGAN00001627900,EGAX00001607544,EGA00001409650,2018-02-16 23:51:10+01,2024-01-17 16:29:41.757737+01
2,EGAR00001652886,fastq,\N,EGAN00001627771,EGAX00001607545,EGA00001409650,2018-02-16 23:51:10+01,2024-01-17 16:29:41.757737+01
3,EGAR00001652887,fastq,\N,EGAN00001627721,EGAX00001607546,EGA00001409650,2018-02-16 23:51:10+01,2024-01-17 16:29:41.757737+01
4,EGAR00001652888,fastq,\N,EGAN00001627851,EGAX00001607547,EGA00001409650,2018-02-16 23:51:10+01,2024-01-17 16:29:41.757737+01

In [27]:
filepath = dirpath / "sample_file.tsv"
assert filepath.exists()
df = pd.read_csv(filepath , sep="\t")
print(df.nunique())
df.head()

sample_accession_id    348
sample_alias           348
file_name              696
file_accession_id      696
dtype: int64

,sample_accession_id,sample_alias,file_name,file_accession_id
0,EGAN00001627665,SAMf2ce197162ce,GO29293_RNAseq_GO29293_ngs_rna_targrna_rnaacce...,EGAF00001873319
1,EGAN00001627665,SAMf2ce197162ce,GO29293_RNAseq_GO29293_ngs_rna_targrna_rnaacce...,EGAF00001873320
2,EGAN00001627666,SAM698d8d76b934,GO29293_RNAseq_GO29293_ngs_rna_targrna_rnaacce...,EGAF00001873573
3,EGAN00001627666,SAM698d8d76b934,GO29293_RNAseq_GO29293_ngs_rna_targrna_rnaacce...,EGAF00001873574
4,EGAN00001627667,SAMc1b27bc16435,GO29293_RNAseq_GO29293_ngs_rna_targrna_rnaacce...,EGAF00001873115

In [28]:
filepath = dirpath / "samples.tsv"
assert filepath.exists()
df = pd.read_csv(filepath , sep="\t")
print(df.nunique())
df.head()

accession_id               348
alias                      348
title                      347
description                347
biological_sex               2
subject_id                 347
phenotype                    1
extra_attributes           348
submission_accession_id      1
created_at                  17
edited_at                    1
dtype: int64

,accession_id,alias,title,description,biological_sex,subject_id,phenotype,extra_attributes,submission_accession_id,created_at,edited_at
0,EGAN00001627665,SAMf2ce197162ce,tumor RNA (10255),RNA extracted from tumor of patient 10255,male,10255,PHENOTYPE,"[{""tag"": ""Baseline ECOG Score"", ""unit"": null, ...",EGA00001394483,2018-01-05 22:36:44+01,2023-06-15 15:10:05.25523+02
1,EGAN00001627666,SAM698d8d76b934,tumor RNA (10101),RNA extracted from tumor of patient 10101,female,10101,PHENOTYPE,"[{""tag"": ""Baseline ECOG Score"", ""unit"": null, ...",EGA00001394483,2018-01-05 22:36:44+01,2023-06-15 15:10:05.25523+02
2,EGAN00001627667,SAMc1b27bc16435,tumor RNA (10230),RNA extracted from tumor of patient 10230,male,10230,PHENOTYPE,"[{""tag"": ""Baseline ECOG Score"", ""unit"": null, ...",EGA00001394483,2018-01-05 22:36:45+01,2023-06-15 15:10:05.25523+02
3,EGAN00001627668,SAM85e41e7f33f9,tumor RNA (10264),RNA extracted from tumor of patient 10264,male,10264,PHENOTYPE,"[{""tag"": ""Baseline ECOG Score"", ""unit"": null, ...",EGA00001394483,2018-01-05 22:36:45+01,2023-06-15 15:10:05.25523+02
4,EGAN00001627669,SAMf275eb859a39,tumor RNA (10150),RNA extracted from tumor of patient 10150,male,10150,PHENOTYPE,"[{""tag"": ""Baseline ECOG Score"", ""unit"": null, ...",EGA00001394483,2018-01-05 22:36:45+01,2023-06-15 15:10:05.25523+02

In [29]:
filepath = dirpath / "study_experiment_run_sample.tsv"
assert filepath.exists()
df = pd.read_csv(filepath , sep="\t")
print(df.nunique())
df.head()

study_accession_id           1
study_title                  1
study_type                   1
instrument_platform          1
instrument_model             1
library_layout               1
library_name                 1
library_strategy             1
library_source               1
library_selection            1
experiment_accession_id    348
run_accession_id           348
sample_accession_id        348
sample_alias               348
biosample_id               348
sample_title               347
dtype: int64

,study_accession_id,study_title,study_type,instrument_platform,instrument_model,library_layout,library_name,library_strategy,library_source,library_selection,experiment_accession_id,run_accession_id,sample_accession_id,sample_alias,biosample_id,sample_title
0,EGAS00001002556,TGF-β attenuates tumour response to PD-L1 bloc...,Other,ILLUMINA,Illumina HiSeq 2500,PAIRED,\N,RNA-Seq,TRANSCRIPTOMIC,other,EGAX00001607543,EGAR00001652884,EGAN00001627928,SAM00b9e5c52da9,SAMEA104453869,tumor RNA (10208)
1,EGAS00001002556,TGF-β attenuates tumour response to PD-L1 bloc...,Other,ILLUMINA,Illumina HiSeq 2500,PAIRED,\N,RNA-Seq,TRANSCRIPTOMIC,other,EGAX00001607544,EGAR00001652885,EGAN00001627900,SAM0257bbbbd388,SAMEA104453841,tumor RNA (10232)
2,EGAS00001002556,TGF-β attenuates tumour response to PD-L1 bloc...,Other,ILLUMINA,Illumina HiSeq 2500,PAIRED,\N,RNA-Seq,TRANSCRIPTOMIC,other,EGAX00001607545,EGAR00001652886,EGAN00001627771,SAM025b45c27e05,SAMEA104453712,tumor RNA (10346)
3,EGAS00001002556,TGF-β attenuates tumour response to PD-L1 bloc...,Other,ILLUMINA,Illumina HiSeq 2500,PAIRED,\N,RNA-Seq,TRANSCRIPTOMIC,other,EGAX00001607546,EGAR00001652887,EGAN00001627721,SAM032c642382a7,SAMEA104453662,tumor RNA (10166)
4,EGAS00001002556,TGF-β attenuates tumour response to PD-L1 bloc...,Other,ILLUMINA,Illumina HiSeq 2500,PAIRED,\N,RNA-Seq,TRANSCRIPTOMIC,other,EGAX00001607547,EGAR00001652888,EGAN00001627851,SAM0571f17f4045,SAMEA104453792,tumor RNA (10085)